from src import Config, Rules


class Player:

    def __init__(self):
        self.score = 0
        self.lives = Config.Ball.LIVES

    def one_point(self):
        self.score += 1

    def ball_dies(self):
        self.lives -= 1


class Brick:

    def __init__(self, x: float, y: float, color: str):
        """
        Initializes a Brick object and its components.

        Args:
            x (float): X coordinate
            y (float): Y coordinate
            color (str): Brick color
        """
        self.x = x
        self.y = y
        self.color = color
        self.is_destroyed = False


class BrickManager:

    def __init__(self):
        """
        Initializes the object and its components. Stores a list of Brick objects and
        assigns them attributes generated by generate_level method for GameView class
        to draw.
        """
        self.bricks = []
        self.generate_level()

    def generate_level(self) -> None:
        """
        Calculates and generates the grid of bricks for the level.

        Iterates through the configured colors and screen bounds to calculate
        the exact X and Y coordinates for each brick. The generated Brick
        objects are appended directly to the internal `self.bricks` list.
        """
        cell_width = Config.Bricks.CELL_WIDTH
        offset = cell_width / 2

        start_x, end_x = Config.Bricks.X_BOUNDS
        start_y = Config.Bricks.Y_BOUNDS[0]

        for i, color in enumerate(Config.Bricks.COLORS):
            actual_y = start_y - (i * Config.Bricks.ROW_SPACING)

            current_x = start_x

            while current_x < end_x:
                actual_x = current_x + offset

                new_brick = Brick(actual_x, actual_y, color)
                self.bricks.append(new_brick)

                current_x += cell_width


class Paddle:

    def __init__(self, start_x: float, start_y: float) -> None:
        self.x = start_x
        self.y = start_y
        self.speed = Config.Paddle.SPEED
        self.x_bounds = Rules.paddle_x_limit()

        self.is_moving_left = False
        self.is_moving_right = False

    def press_left(self) -> None:
        self.is_moving_left = True

    def release_left(self) -> None:
        self.is_moving_left = False

    def press_right(self) -> None:
        self.is_moving_right = True

    def release_right(self) -> None:
        self.is_moving_right = False

    def move(self) -> None:

        if self.is_moving_left:
            self.x -= self.speed
        if self.is_moving_right:
            self.x += self.speed

        self.x = max(-self.x_bounds, min(self.x_bounds, self.x))


class Ball:

    def __init__(self, start_x: float, start_y: float):
        self.x = start_x
        self.y = start_y
        self.x_move = 0.0
        self.y_move = 0.0
        self.in_play = False

    def set_velocity(self, dx: float, dy: float):
        self.x_move = dx
        self.y_move = dy

    def move(self) -> None:
        self.x += self.x_move
        self.y += self.y_move

    def bounce_x(self) -> None:
        self.x_move *= -1

    def bounce_y(self) -> None:
        self.y_move *= -1

    def reset_position(self, x: float, y: float) -> None:
        self.x = x
        self.y = y
        self.x_move = 0.0
        self.y_move = 0.0
        self.in_play = False